<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1NV6O7N" failures="2" tests="17" name="Default test" time="4.118" errors="0" timestamp="2022-11-25T11:22:41 IST">
  <testcase classname="API_PUT_TestCases.PUT_TestCases" name="TC_01_PUT_Connection_check" time="0.011"/>
  <testcase classname="API_PUT_TestCases.PUT_TestCases" name="TC_02_PUT_Connection_Response_check" time="0.005"/>
  <testcase classname="API_PUT_TestCases.PUT_TestCases" name="TC_03_PUT_StatusCode_Check" time="0.004"/>
  <testcase classname="API_PUT_TestCases.PUT_TestCases" name="TC_04_PUT_Response_text_check" time="0.004"/>
  <testcase classname="API_PUT_TestCases.PUT_TestCases" name="TC_05_PUT_Response_Time_Check" time="0.009"/>
  <testcase classname="API_GET_TestCases.GET_TEST_CASES" name="TC01_api_connect_check" time="1.195"/>
  <testcase classname="API_GET_TestCases.GET_TEST_CASES" name="TC02_Check_Response_code" time="0.066"/>
  <testcase classname="API_GET_TestCases.GET_TEST_CASES" name="TC03_get_Complete_Response" time="0.324"/>
  <testcase classname="API_GET_TestCases.GET_TEST_CASES" name="TC04_Check_Time_Received" time="0.045"/>
  <testcase classname="API_GET_TestCases.GET_TEST_CASES" name="TC05_Receive_body_as_string" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at API_GET_TestCases.GET_TEST_CASES.TC05_Receive_body_as_string(GET_TEST_CASES.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC05_Receive_body_as_string -->
  <testcase classname="API_GET_TestCases.GET_TEST_CASES" name="TC06_Check_session_ID" time="0.013">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.isEmpty()&amp;quot; because &amp;quot;sessionID&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "sessionID" is null
at API_GET_TestCases.GET_TEST_CASES.TC06_Check_session_ID(GET_TEST_CASES.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC06_Check_session_ID -->
  <testcase classname="API_POST_TestCases.POST_Test_Cases" name="TC_01_POST_Connection_Check" time="1.004"/>
  <testcase classname="API_POST_TestCases.POST_Test_Cases" name="TC_02_POST_Check_Response_Text" time="0.003"/>
  <testcase classname="API_POST_TestCases.POST_Test_Cases" name="TC_03_POST_Check_Response_Code" time="0.004"/>
  <testcase classname="API_POST_TestCases.POST_Test_Cases" name="TC_04_POST_Check_Response_Time" time="0.008"/>
  <testcase classname="API_POST_TestCases.POST_Test_Cases" name="TC_05_POST_Check_Session_ID" time="0.023"/>
  <testcase classname="API_POST_TestCases.POST_Test_Cases" name="TC_06_POST_Check_getResponse_string" time="0.002"/>
</testsuite> <!-- Default test -->
